// messages.js
export const SET_MESSAGES = 'SET_MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const SET_NOTIMESSAGE = 'SET_NOTIMESSAGE'
export const UNSET_NOTIMESSAGE = 'UNSET_NOTIMESSAGE'
export const CLEAR_NOTIMESSAGE = 'CLEAR_NOTIMESSAGE'
